---
- hosts: all
  become: yes
  tasks:
          - name: Install packages
            apt:
                    name: "{{ tools }}"
                    state: latest
                    update_cache: yes
